### PR TITLE
Revert previous change.

### PR DESCRIPTION
**Pull request by ZHZG**
Fix the defect: next cell will not go into edit mode.

### CODE REVIEW

**Comment by objorke** [comment]
I had a second look at this. What about #25 that supposedly was solved in #26?

**Comment by ZHZG** [comment]
No. But seems that #25 is fixed in HydroD by other changes.

**Comment by ZHZG** [comment]
@objorke, No. But seems that #25 is fixed in HydroD by other changes.

**Comment by objorke** [comment]
OK!

**Pull request merged**
