### PR TITLE
Add Multiselect to FilePicker

### PR DESCRIPTION
**Pull request by gotdibbs**
- Added property to FilePicker to allow for multiselect on the file open dialog.
- Updated other relevant portions (IFileDialogService interface, examples, FilePath property) accordingly.

### CODE REVIEW

**Comment by objorke** [comment]
Cool, thanks for including the example.

**Comment by objorke** [comment]
Found issue #50

**Comment by objorke** [comment]
Fixed #50 + StyleCop issues

**Comment by gotdibbs** [comment]
Ah, sorry for missing that section of the code, but thanks for the fix!

**Pull request merged**
